<?php
require_once("inc/access_control.php");
require_once('inc/mail/mail.php');
require_once("inc/get_database.php");
AccessControl::requireType("Admin");
if(isset($_POST["proccess"])&&$_POST["proccess"]){
	include("inc/pages/register/register_proccess.php");
}else{
	include("inc/pages/register/register_form.php");
}
?>
